import assert from 'node:assert/strict';import fs from'node:fs';import{review,isDue,blankProgress}from'../js/scheduler.js';import{makeOptions}from'../js/quiz.js';import{buildFlashDeck,filterFlashcards}from'../js/flashcards.js';import{examResult}from'../js/exam.js';import{normalizeInfraction}from'../js/infractions-data.js';import{availableQuestionTypes,buildInfractionQuestion,buildInfractionQuiz,infractionFlashFaces}from'../js/infractions-engine.js';
const root=new URL('../',import.meta.url),data=JSON.parse(fs.readFileSync(new URL('data/panneaux_code.json',root),'utf8'));
assert.equal(data.length,243);assert(data.filter(x=>x.active).length>=169);assert.equal(new Set(data.map(x=>x.code)).size,243);assert.equal(data.filter(x=>x.active&&['Exclu','À vérifier','Incomplet'].includes(x.validation)).length,0);
const active=data.filter(x=>x.active),options=makeOptions(active[0],active);assert.equal(options.length,4);assert.equal(new Set(options.map(x=>x.name)).size,4);assert(options.some(x=>x.code===active[0].code));
const flashDeck=buildFlashDeck(active);assert.equal(flashDeck.length,active.length);assert.equal(filterFlashcards(active,{},{}).length,active.length);
const now=new Date('2026-07-15T08:00:00Z'),hard=review(blankProgress(),'hard',now),correct=review(hard,'correct',now),wrong=review(correct,'wrong',now);assert.equal(hard.intervalDays,1);assert.equal(correct.intervalDays,3);assert.equal(wrong.intervalDays,1);assert(isDue(wrong,new Date('2026-07-16T08:00:00Z')));
const result=examResult([{sign:{code:'A'},answer:'A'},{sign:{code:'B'},answer:'C'}]);assert.equal(result.correct,1);assert.equal(result.scorePercent,50);
const infractions=JSON.parse(fs.readFileSync(new URL('data/infractions_code.json',root),'utf8')).map(normalizeInfraction);assert.equal(infractions.length,39);assert.equal(infractions.filter(x=>x.active).length,39);assert.equal(new Set(infractions.map(x=>x.id)).size,39);assert(infractions.every(x=>x.officialSource&&x.legalReference));assert(data.every(x=>fs.existsSync(new URL(String(x.image).replace(/^\.\.\/assets\//,'assets/'),root))));
for(const item of infractions){for(const type of availableQuestionTypes(item)){const q=buildInfractionQuestion(item,infractions,type);assert(q.answer!==null&&q.answer!==undefined&&q.answer!=='');assert(q.options.some(x=>x.value===q.answer));assert.equal(new Set(q.options.map(x=>x.value)).size,q.options.length);if(type==='fine')assert(item.fineFixed!=null);if(type==='class')assert(item.contraventionClass!=null)}}
const infQuiz=buildInfractionQuiz(infractions,20);assert.equal(infQuiz.length,20);assert(infQuiz.every(q=>q.options.length>=2));const faces=infractionFlashFaces(infractions[0],'infraction-sanctions',infractions,{});assert(faces.front&&faces.back);const mixed=[...active.slice(0,5).map(x=>`panel:${x.code}`),...infractions.slice(0,5).map(x=>`inf:${x.id}`)];assert.equal(mixed.length,10);
console.log('Tests JS réussis : panneaux, 39 infractions, quiz, flashcards, planification, examen et mode mixte.');
